language: python
python:
  - "2.7"
services:
  - postgresql
before_script:
  - psql -c 'create database ringotest;' -U postgres
# command to install dependencies,
# Deactivate the installation of formbar if you want 
# to build with a release version of formbar and not with the latest development version
install:
  - pip install git+https://github.com/ringo-framework/formbar
  - pip install -e .\[tests\]
# command to run tests
script: 
  - ringo-admin db init --config test.ini
  - py.test --app-config test.ini
